name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/spec-check-filter-release.yaml@fixed-schema
    permissions:
      contents: write
      packages: write
      checks: write
